/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.text.DecimalFormat;

/**
 *
 * @author root
 */
public class MainWindow extends javax.swing.JFrame {
    
    private boolean init;
    
    /**
     * Creates new form window
     */
    public MainWindow() {
        init = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        developers = new javax.swing.JLabel();
        exchangeRate = new javax.swing.JTextField();
        currency1 = new javax.swing.JTextField();
        currency2 = new javax.swing.JTextField();
        toCurrency2 = new javax.swing.JButton();
        toCurrency1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        developers.setFont(new java.awt.Font("Cantarell", 1, 10)); // NOI18N
        developers.setText("Geraldo Rodrígues & David Medina 2017");

        exchangeRate.setText("Índice");
        exchangeRate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                exchangeRateFocusGained(evt);
            }
        });

        currency1.setText("Divisa origen");
        currency1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                currency1FocusGained(evt);
            }
        });

        currency2.setText("Divisa destino");
        currency2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                currency2FocusGained(evt);
            }
        });

        toCurrency2.setText("->");
        toCurrency2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toCurrency2ActionPerformed(evt);
            }
        });

        toCurrency1.setText("<-");
        toCurrency1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toCurrency1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(currency1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exchangeRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toCurrency2)
                            .addComponent(toCurrency1))
                        .addGap(44, 44, 44)
                        .addComponent(currency2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(developers)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exchangeRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toCurrency2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currency1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toCurrency1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(currency2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)))
                .addComponent(developers)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void currency2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_currency2FocusGained
        currency2.setText("");
    }//GEN-LAST:event_currency2FocusGained

    private void currency1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_currency1FocusGained
        currency1.setText("");
    }//GEN-LAST:event_currency1FocusGained

    private void exchangeRateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_exchangeRateFocusGained
        if(init == false) 
            init = true;
        else
            exchangeRate.setText("");

    }//GEN-LAST:event_exchangeRateFocusGained

    private void toCurrency2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toCurrency2ActionPerformed
        try {
            this.currency2.setText(checkInput(this.currency1));
        } catch (NumberFormatException e) {
            System.out.println("Esto no es un número float");
        }
    }//GEN-LAST:event_toCurrency2ActionPerformed

    private void toCurrency1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toCurrency1ActionPerformed
        try {
            this.currency1.setText(checkInput(this.currency2));
        } catch (NumberFormatException e) {
            System.out.println("Esto no es un número float");
        }
    }//GEN-LAST:event_toCurrency1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField currency1;
    private javax.swing.JTextField currency2;
    private javax.swing.JLabel developers;
    private javax.swing.JTextField exchangeRate;
    private javax.swing.JButton toCurrency1;
    private javax.swing.JButton toCurrency2;
    // End of variables declaration//GEN-END:variables
    
    private String checkInput(javax.swing.JTextField textField) {
        Float rate = Float.parseFloat(this.exchangeRate.getText());
            Float currency = Float.parseFloat(textField.getText());
            DecimalFormat df = new DecimalFormat("#.00");
            Float result = Float.parseFloat(df.format(rate.floatValue())) 
                    * Float.parseFloat(df.format(currency.floatValue()));
        return result.toString();
    }
}
